<?php

/**
 * @file
 * Contains janus_ab.module.
 */

/**
 * Implements hook_help().
 */
function janus_ab_help($route_name) {
  if ($route_name !== 'help.page.janus_ab') {
    return '';
  }

  $text = file_get_contents(drupal_get_path('module', 'janus_ab') . '/README.md');

  if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
    return [
      '#markup' => str_replace("\n", '<br />', $text),
      '#allowed_tags' => ['br'],
    ];
  }

  $filters = new \Drupal\filter\FilterPluginCollection(\Drupal::service('plugin.manager.filter'));
  $filter = $filters->get('markdown');
  $text = $filter->process($text, \Drupal::languageManager()->getCurrentLanguage()->getId());

  return $text->getProcessedText();
}